'use client';
import { useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { authApi } from '@/api/auth';
import { useAuth } from '@/context/auth-context';
export type AuthMode='login'|'register'|'forgot'|'reset'|'verify';
export default function AuthForm({mode,token='',adminOnly=false}:{mode:AuthMode;token?:string;adminOnly?:boolean}){
 const {login}=useAuth(),router=useRouter();const [email,setEmail]=useState(''),[name,setName]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[success,setSuccess]=useState(false);
 const titles={login:'Log in',register:'Create your FCA account',forgot:'Recover your password',reset:'Set a new password',verify:'Verify your email'};
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage('');try{if((mode==='register'||mode==='reset')&&password!==confirm)throw Error('Passwords do not match.');if(mode==='login'){await login(email,password);router.push(adminOnly?'/admin':'/');router.refresh();return}const result=mode==='register'?await authApi.register(name,email,password):mode==='forgot'?await authApi.forgot(email):mode==='reset'?await authApi.reset(token,password):await authApi.verify(token);setMessage(result.message);setSuccess(true)}catch(e){setMessage(e instanceof Error?e.message:'The request failed.')}finally{setBusy(false)}}
 async function resend(){setBusy(true);try{setMessage((await authApi.resend(email)).message)}catch(e){setMessage(e instanceof Error?e.message:'The request failed.')}finally{setBusy(false)}}
 return <main className="auth-shell"><section className="card stack"><Link href="/">← Facility Condition Assessment</Link><h1>{adminOnly?"Admin login":titles[mode]}</h1>{adminOnly&&<p className="muted">Sign in with an account assigned the Admin role.</p>}{(mode==='verify'||mode==='reset')&&!token?<p role="alert">Open the link in your email to continue.</p>:<form onSubmit={e=>void submit(e)} className="stack"><fieldset disabled={busy||success&&mode!=='login'} className="assessment-fields stack">{mode==='register'&&<label>Full name<input required maxLength={160} autoComplete="name" value={name} onChange={e=>setName(e.target.value)} /></label>}{['login','register','forgot'].includes(mode)&&<label>Email address<input type="email" required autoComplete="email" maxLength={254} value={email} onChange={e=>setEmail(e.target.value)} /></label>}{['login','register','reset'].includes(mode)&&<label>Password<input type="password" required minLength={mode==='login'?1:12} maxLength={128} autoComplete={mode==='login'?'current-password':'new-password'} value={password} onChange={e=>setPassword(e.target.value)} /></label>}{['register','reset'].includes(mode)&&<><p className="muted">Use at least 12 characters including lower-case letters, capital letters, numbers and special characters.</p><label>Confirm password<input required type="password" autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)} /></label></>}<button className="btn" type="submit">{busy?'Please wait…':mode==='verify'?'Verify email':titles[mode]}</button></fieldset></form>}{message&&<p className="auth-message" role="status">{message}</p>}<div className="auth-links"><Link href="/login">Log in</Link><Link href="/register">Register</Link><Link href="/forgot-password">Forgot password?</Link></div>{mode==='login'&&<button disabled={busy||!email} className="btn outline" onClick={()=>void resend()}>Resend verification email</button>}</section></main>
}
