import {requestDeletion} from '../models/deletion.model.js';
import type { Request,Response } from 'express';
import { pool,transaction } from '../configs/database.js';
import * as model from '../models/project.model.js';
import type { ProjectInput } from '../types/domain.js';
import { HttpError } from '../src/utils/errors.js';
const id=(req:Request)=>String(req.params.id);
export async function list(req:Request,res:Response){res.json(await model.list(req.auth!.userId))}
export async function get(req:Request,res:Response){res.json(await transaction(async db=>{await model.ownedProject(db,id(req),req.auth!.userId,true);return model.read(db,id(req),req.auth!.userId)}))}
export async function create(req:Request,res:Response){res.status(201).json(await transaction(db=>model.insert(db,req.auth!.userId,req.validated as ProjectInput)))}
export async function update(req:Request,res:Response){res.json(await transaction(async db=>{const input=req.validated as ProjectInput;if(req.auth!.role!=='admin'){const stored=await model.read(db,id(req),req.auth!.userId);for(const key of ['name','assetNumber','client','discipline','companyName','companyAddress','clientAddress'] as const)Object.assign(input,{[key]:stored[key]});}return model.update(db,id(req),req.auth!.userId,input)}))}
export async function archive(req:Request,res:Response){if(req.auth!.role!=='admin'){const pending=await transaction(async db=>{const row=await model.ownedProject(db,id(req),req.auth!.userId,true);return requestDeletion(db,id(req),req.auth!.userId,'project',id(req),row.name)});res.status(202).json(pending);return}await transaction(async db=>{await model.ownedProject(db,id(req),req.auth!.userId,true);await db.query('UPDATE projects SET deleted_at=now(),updated_at=now(),version=version+1 WHERE id=$1',[id(req)]);await model.audit(db,req.auth!.userId,id(req),'project.archived')});res.json({ok:true})}
export async function restore(req:Request,res:Response){const {assetNumber,projectName}=req.validated as {assetNumber:string;projectName?:string};const result=await transaction(async db=>{const rows=(await db.query('SELECT id FROM projects WHERE owner_id=$1 AND lower(trim(asset_number))=lower($2) AND deleted_at IS NOT NULL AND ($3::text IS NULL OR name=$3) ORDER BY deleted_at DESC FOR UPDATE',[req.auth!.userId,assetNumber,projectName||null])).rows;if(!rows.length)throw new HttpError(404,'No archived project was found for this asset number.');if(rows.length>1)throw new HttpError(409,'More than one archived project uses this asset number. Enter the project name as well.','AMBIGUOUS_ASSET',{needsProjectName:true});await db.query('UPDATE projects SET deleted_at=NULL,updated_at=now(),version=version+1 WHERE id=$1',[rows[0].id]);await model.audit(db,req.auth!.userId,rows[0].id,'project.restored');return model.read(db,rows[0].id,req.auth!.userId)});res.json(result)}
export async function audit(req:Request,res:Response){await model.ownedProject(pool,id(req),req.auth!.userId);const rows=await pool.query('SELECT action,occurred_at AS "occurredAt" FROM audit_events WHERE project_id=$1 ORDER BY occurred_at DESC LIMIT 200',[id(req)]);res.json({events:rows.rows})}
