import {requestDeletion} from '../models/deletion.model.js';
import type { Request,Response } from 'express';
import { randomUUID } from 'node:crypto';
import { pipeline } from 'node:stream/promises';
import { pool,transaction } from '../configs/database.js';
import { storage } from '../configs/blob.js';
import { ownedProject,read,audit,writePayload } from '../models/project.model.js';
import * as attachments from '../models/attachment.model.js';
import { validateFile,putBlob,deleteBlob } from '../src/services/blob.service.js';
import { payloadSchema } from '../src/validation/project.js';
import { HttpError } from '../src/utils/errors.js';
import type { AssetKind } from '../types/domain.js';
import { logger } from '../configs/logger.js';
const projectId=(req:Request)=>String(req.params.id);
const kind=(req:Request)=>req.params.kind as AssetKind;
async function compensate(key:string){try{await deleteBlob(key)}catch{await pool.query('INSERT INTO blob_deletions(blob_key) VALUES($1) ON CONFLICT DO NOTHING',[key])}}
export async function uploadAsset(req:Request,res:Response){const id=projectId(req),userId=req.auth!.userId,assetKind=kind(req);await ownedProject(pool,id,userId);const file=await validateFile(req.file,assetKind);const key=await putBlob(id,req.file!.buffer,file.contentType);try{await transaction(async db=>{await ownedProject(db,id,userId,true);const old=(await db.query('SELECT * FROM attachments WHERE project_id=$1 AND kind=$2',[id,assetKind])).rows[0];if(old&&req.auth!.role!=='admin')throw new HttpError(403,'Request admin approval before replacing the existing file.','ADMIN_APPROVAL_REQUIRED');if(old){await db.query('INSERT INTO blob_deletions(blob_key) VALUES($1) ON CONFLICT DO NOTHING',[old.blob_key]);await db.query('DELETE FROM attachments WHERE id=$1',[old.id])}await db.query('INSERT INTO attachments(id,project_id,kind,blob_key,original_name,content_type,size_bytes,sha256,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)',[randomUUID(),id,assetKind,key,file.name,file.contentType,req.file!.size,file.sha256,userId]);await db.query('UPDATE projects SET updated_at=now() WHERE id=$1',[id]);await audit(db,userId,id,'attachment.uploaded')});const names={'site-plan':'sitePlanName','facility-logo':'facilityLogoName','company-logo':'companyLogoName','assessor-signature':'assessorSignatureName'} as const;res.status(201).json({[names[assetKind as keyof typeof names]]:file.name})}catch(error){await compensate(key);throw error}}
export async function uploadPhoto(req:Request,res:Response){const id=projectId(req),userId=req.auth!.userId;await ownedProject(pool,id,userId);const file=await validateFile(req.file,'photo');let payload;try{payload=payloadSchema.parse(JSON.parse(req.body.payload||''))}catch{throw new HttpError(400,'Invalid assessment payload.')}const index=Number(req.body.captureIndex),version=Number(req.body.version);if(!Number.isInteger(index)||index<0||index>=payload.captures.length||!Number.isInteger(version))throw new HttpError(400,'Select a valid component.');const key=await putBlob(id,req.file!.buffer,file.contentType);try{const project=await transaction(async db=>{const old=await ownedProject(db,id,userId,true);if(version!==old.version)throw new HttpError(409,'Project changed. Reopen it before uploading.','VERSION_CONFLICT');await writePayload(db,id,payload,userId);const submitted=payload.captures[index];const captureId=submitted.id||(await db.query('SELECT c.id FROM captures c JOIN elements e ON e.id=c.element_id JOIN functional_areas a ON a.id=e.area_id WHERE c.project_id=$1 AND a.name=$2 AND e.name=$3 AND c.component=$4 AND c.discipline=$5 ORDER BY c.position DESC LIMIT 1',[id,submitted.area,submitted.element,submitted.component,submitted.discipline])).rows[0]?.id;if(!captureId)throw new HttpError(400,'Component not found.');const count=(await db.query('SELECT count(*)::int AS total FROM attachments WHERE capture_id=$1',[captureId])).rows[0].total;if(count>=10)throw new HttpError(400,'A component can have at most 10 photos.');await db.query('INSERT INTO attachments(id,project_id,capture_id,kind,blob_key,original_name,content_type,size_bytes,sha256,created_by) VALUES($1,$2,$3,\'photo\',$4,$5,$6,$7,$8,$9)',[randomUUID(),id,captureId,key,file.name,file.contentType,req.file!.size,file.sha256,userId]);await db.query('UPDATE projects SET version=version+1,updated_at=now() WHERE id=$1',[id]);await audit(db,userId,id,'photo.uploaded');return read(db,id,userId)});res.status(201).json({project})}catch(error){await compensate(key);throw error}}
export async function download(req:Request,res:Response){const file=await attachments.getAttachment(pool,projectId(req),req.auth!.userId,req.params.photoId?'photo':String(req.params.kind),req.params.photoId?String(req.params.photoId):undefined);const blob=await storage.read(file.blob_key);res.set({'Content-Type':file.content_type,'Cache-Control':'private, no-store','Content-Disposition':`${file.content_type.startsWith('image/')?'inline':'attachment'}; filename*=UTF-8''${encodeURIComponent(file.original_name)}`,'X-Content-Type-Options':'nosniff'});if(blob.size!=null)res.set('Content-Length',String(blob.size));try{await pipeline(blob.stream,res)}catch(error){logger.warn({requestId:req.requestId,error:error instanceof Error?error.message:'Stream failed'},'Attachment stream interrupted');if(!res.headersSent)throw error}}
export async function remove(req:Request,res:Response){const result=await transaction(async db=>{const id=projectId(req),userId=req.auth!.userId;await ownedProject(db,id,userId,true);const file=await attachments.getAttachment(db,id,userId,req.params.photoId?'photo':String(req.params.kind),req.params.photoId?String(req.params.photoId):undefined);if(req.auth!.role!=='admin'){return requestDeletion(db,id,userId,'attachment',file.id,file.original_name)}const version=await attachments.remove(db,id,userId,file.kind,file.kind==='photo'?file.id:undefined);await audit(db,userId,id,'attachment.removed');return {ok:true,version}});res.status('pending' in result?202:200).json(result)}
